Handle files with UTF8 Byte Order Mark properly (fixes #4)
tafia/quick-csv pull request #5
Opened 2016-09-26 10:53 UTC by msiemens

See #4

The patch fixes the bug but somehow there's still a weird coner case that it fails to parse `\xef\xbb\xbf\"abc\",\"xyz\"` (without the trailing newline), returning a UnexpextedQuote error. I don't really get why this happens only when there was a BOM present (parses successfully without the BOM).

2016-09-28 13:48 UTC, tafia requested changes
Thanks for the PR and again sorry for the late answer. as I told you i don't have much time. 

I'm not very familiar with BOM so I may be totally wrong. As I understand it, it happens only at the very beginning of the stream. So we should probably have a dedicated function called once and avoid checking for `is_first` every time.

2016-09-29 14:57 UTC, msiemens commented
> As I understand it, it happens only at the very beginning of the stream. So we should probably have a dedicated function called once and avoid checking for is_first every time.

That's right. The first approach wasn't really elegant because I didn't know that it's okay to call `BufRead::fill_buf` multiple times without causing problems. I've now changed the PR to only try to skip the BOM when creating the `CSV` instance. The bug with the trailing newline is now gone too!

2016-09-29 15:56 UTC, tafia commented
Thanks for this.
Looks very good.

2016-09-29 15:56 UTC, merged

2016-09-29 16:03 UTC, tafia reviewed
Published v0.1.6 (removed an unused function too)
Thanks again

2016-09-29 21:47 UTC, msiemens commented
Awesome, thank you!